Description: >
    Deepak Madisetty / Udacity NanoDegree Capstone Project
   
Parameters:

    StackName:
        Description: A stack name that will be prefixed to resource names
        Type: String

Resources:
  
  eksServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  EKSCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: capstone-eks-cluster
      Version: '1.14'
      RoleArn: !GetAtt eksServiceRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds: 
          - Fn::ImportValue: !Sub ${StackName}-CPSG
        SubnetIds:
          - Fn::ImportValue: !Sub "${StackName}-PUB1-SN"
          - Fn::ImportValue: !Sub "${StackName}-PUB2-SN"
          - Fn::ImportValue: !Sub "${StackName}-PRI1-SN"
          - Fn::ImportValue: !Sub "${StackName}-PRI2-SN"

Outputs:
  eksServiceRole:
    Description: The node instance role
    Value: !GetAtt eksServiceRole.Arn
    Export:
        Name: !Sub ${StackName}-eksServiceRole

  EKSCluster: 
    Description: EKS Cluster ID
    Value: !Ref EKSCluster
    Export: 
        Name: !Sub ${StackName}-EKSCluster