apiVersion: v1
kind: Service
metadata:
  name: capstone-app
spec:
  selector:
    app: capstone-app
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31910