apiVersion: v1
kind: Service
metadata:
  name: capstone-app
spec:
  selector:
    app: capstone-app
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31910
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
  labels:
    app: capstone-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
      - image: shivam/capstone
        imagePullPolicy: Always
        name: capstone-app
        ports:
        - containerPort: 80
          protocol: TCP