apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-capstone
  labels:
    app: capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 25%
       maxUnavailable: 25%  
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: deepakmadisetty/capstone:latest
        ports:
        - containerPort: 80